bucket         = "dev-application-terraform-state"
#bucket         = "dev-account-ap-southeast-1-application-terraform-state"
key            = "application/infra/terraform.tfstate"
region         = "ap-southeast-1"
encrypt        = true
dynamodb_table = "dev-application-terraform-locks"
#dynamodb_table = "dev-account-ap-southeast-1-application-terraform-locks"